### ISSUE TITLE
Add automatic log file rotation

### ISSUE THREAD

**Issue by cfnptr** [cfnptr/logy#1]
Remove or create new log file after some time.

**Comment by NCatalani** [comment]
Will we rotate logs based on file size or time?
The amount of logs already rotated kept should be also passed as a parameter?

**Comment by cfnptr** [comment]
> Will we rotate logs based on file size or time?

I think we should support both log rotation variants.

> The amount of logs already rotated kept should be also passed as a parameter?

What do you mean? I think that on logger creation should be passed rotation type (size and/or time), and how many compressed logs to store. On log rotation event close current file, compress it and rename to current date and time or increment id, then open new log file.

**Comment by cfnptr** [comment]
Added log file rotation base on time. https://github.com/cfnptr/logy/commit/562c9522bcd18a2eecef6ad2a3eec68a552964c5
